Q1. For (n,k).(k,m) matrix multiplication, k time multiplication operation takes place to give one element and (k-1) times addition takes place for the same.
Total multiplication = n*m*k
Total addition = n*m*(k-1)
Total operations = n*m*(2k-1)

In [1]:
#Q2 I will be considering a 3*3 matrix
import numpy as np
import timeit

start1 = timeit.default_timer()
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
B = [[10,11,12],
     [13,14,15],
     [16,17,18]]

out = [([0]*3) for i in range(3)]

for i in range(3):
    for j in range(3):
        for k in range(3):
            out[i][j] = out[i][j] + A[i][k]*B[k][j]
end1 = timeit.default_timer()
print(end1-start1)
print(out)

A = np.array(A)
B = np.array(B)
start2 = timeit.default_timer()
outnp = np.dot(A,B)
end2 = timeit.default_timer()
print(end2-start2)
print(outnp)

0.00015460000000011576
[[84, 90, 96], [201, 216, 231], [318, 342, 366]]
0.00019539999999995672
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


Multiplication with numpy is significantly better with time.
Numpy arrays are stored in contigous memory block, allowing it to perform multiplication effectively. On the other hand, python lists are stored in fragmented way which slows down the operations.
Also numpy uses pre compiled and optimised functions resulting in lesser time consumption.

In [2]:
#Q3
arr = np.random.rand(10**3)
#using given method
# arr2 = arr
# start = timeit.default_timer()

# if len(arr2)%2==0:
#     for i in range((len(arr2)//2)+1):
#         maxx = -1
#         secmaxx = maxx
#         for j in range(len(arr)):
#             num = arr[j]
#             if num>maxx:
#                 secmaxx = maxx
#                 maxx = num
#                 arr2 = np.delete(arr2,j)
#     med1  = (maxx+secmaxx)/2
# end = timeit.default_timer()
# print("Median with looping ",med1)
# print("Time taken ",end-start)

#A better method can be by first sorting the array and then taking the middle element
start = timeit.default_timer()

sort_arr = sorted(arr)
n = len(arr)
if n % 2 == 1:  # Odd number of elements
     med2 = sort_arr[n // 2]  # Middle element is the median
else:  # Even number of elements
    med2 = (sort_arr[n // 2 - 1] + sort_arr[n // 2]) / 2  # Average of middle two elements

end = timeit.default_timer()

print("Median with sorting ",med2)
print("Time taken ", end-start)

start = timeit.default_timer()
med3 = np.median(arr)
end = timeit.default_timer()

print("Median with numpy ",med3)
print("Time taken ", end-start)

Median with sorting  0.481243771717556
Time taken  0.0004347999999998464
Median with numpy  0.481243771717556
Time taken  0.000520800000000321


Q4
wrt x:
$2*x*y+y^3*cos(x)$
wrt y:
$x^2*+3*y^2*sin(x)$

In [3]:
#Q7

student_records = {
    2022: {
        'Branch 1': {
            'Roll Number': 1,
            'Name': 'N',
            'Marks': {
                'Maths': 100,
                'English': 70
            }
        },
        'Branch 2': {
        }
    },
    2023: {
        'Branch 1': {},
        'Branch 2': {}
    },
    2024: {
        'Branch 1': {},
        'Branch 2': {}
    },
    2025: {
        'Branch 1': {},
        'Branch 2': {}
    }
}
student_records

{2022: {'Branch 1': {'Roll Number': 1,
   'Name': 'N',
   'Marks': {'Maths': 100, 'English': 70}},
  'Branch 2': {}},
 2023: {'Branch 1': {}, 'Branch 2': {}},
 2024: {'Branch 1': {}, 'Branch 2': {}},
 2025: {'Branch 1': {}, 'Branch 2': {}}}

In [4]:
#Q9
import matplotlib.pyplot as plt


def fn(x):
    #return x
    #return x**2
    #return (x**3)/100
    #return np.sin(x)
    #return (np.sin(x))/x
    #return np.log(x)
    return np.exp(x)

x_values = np.arange(0.5, 100.0, 0.5)

y_values = fn(x_values)

plt.plot(x_values, y_values)

# Adding labels and title
plt.xlabel('x')
plt.ylabel('y')

plt.show()

In [5]:
#Q10
import pandas as pd
random_matrix = np.random.uniform(1, 2, size=(20, 5))

df = pd.DataFrame(random_matrix, columns=['a', 'b', 'c', 'd', 'e'])
col_idx = df.std().idxmax()
row_idx = df.mean(axis=1).idxmin()

print("Column with highest std ", col_idx)
print("Row with lowest mean ",row_idx)

Column with highest std  a
Row with lowest mean  11


In [6]:
#Q11

df['f'] = df[['a', 'b', 'c', 'd', 'e']].sum(axis=1)
df['g'] = np.where(df['f'] < 8, 'LT8', 'GT8')
 
lt8rows = df[df['g'] == 'LT8'].shape[0]

lt8_std = df.loc[df['g'] == 'LT8', 'f'].std()
gt8_std = df.loc[df['g'] == 'GT8', 'f'].std()

print("Total rows with lt8: ", lt8rows)
print("Standard Devaiation of f where g is lt8: ",lt8_std)
print("std of f where g is gt8: ", gt8_std)

Total rows with lt8:  18
Standard Devaiation of f where g is lt8:  0.39228172929464616
std of f where g is gt8:  0.24590373726609618


In [7]:
#Q12
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([7,8,9])
result = a + b

print("A: \n", a)
print("B: \n",b)

print("Output\n", result)

A: 
 [[1 2 3]
 [4 5 6]]
B: 
 [7 8 9]
Output
 [[ 8 10 12]
 [11 13 15]]
